## THIS FILE HAS BEEN AUTOGENERATED FOR USE WITH CATKIN AND IS NOT SUPPOSED TO BE TRACKED BY GIT!
## DO NOT MANUALLY INVOKE THIS setup.py, USE CATKIN INSTEAD

from setuptools import setup
from catkin_pkg.python_setup import generate_distutils_setup

# fetch values from package.xml
setup_args = generate_distutils_setup(package_xml_path='/home/max/phd/radar/ws1/src/beamdatagenerator',
    packages=['beamdatagenerator'],
    package_data={'': ['']},
    package_dir={'': 'src'})

setup(**setup_args)
